---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)

    # shiny,
    # dplyr,
    # DT,
    # ggplot2,
    # stringr,
    # vat,
    # scales
    # 
```

## Shiny Atlantis

Install these dependencies. 

```{r,eval=FALSE}
install.packages(c("DT", "devtools", "dplyr", "ggplot2", "scales", "shiny", "stringr"))
devtools::install_github(repo = "mareframe/vat")
```

Install the package (from local Git). 

```{r,eval=FALSE}
devtools::install_git("/home/shared/tools/Atlantis/ShinyAtlantis")
```

Load packages (can fix by namespace later)

```{r}
library(dplyr)
library(shiny)
library(DT)

library(ggplot2)

library(stringr)
library(vat)
library(scales)

library(ShinyAtlantis)
```

## Distribution tool

```{r,eval=FALSE}
bgmfile <- system.file("extdata", "BanzareAtlantis.bgm", package= "ShinyAtlantis")

## namespace later
## there's a make.map.object for setup as well as distribution and they are different
mapobject <- ShinyAtlantis:::make.map.objectDistribution(bgmfile)
sh.dist(mapobject)

```

## Setup tools


```{r,eval=FALSE}
## these are globals (for easy shiny use, need to sort this out)
def.all.file <- system.file("extdata", "paramdefns.csv", package= "ShinyAtlantis")
def.grp.file <- system.file("extdata", "grpTemplates.csv", package = "ShinyAtlantis")

# Anatarctic model files 
grpfile <- system.file("extdata",  "AntarcticGroups.csv", package= "ShinyAtlantis")
prmfile <- system.file("extdata",  "SO90_biol.prm", package= "ShinyAtlantis")
# generate the object of data that is read in by the shiny app (takes a few minutes)
obj.ast.Antarctic <- ShinyAtlantis:::make.setup.object(bgmfile, grpfile, prmfile)
ShinyAtlantis:::sh.ast(obj.ast.Antarctic) # run the shiny App

```