---
title: "shdist Run"
author: "Shane Richards, Michael Sumner"
date: "1/22/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## shdist.R

```{r,eval=FALSE}
# shdist.R
# 15/01/2016
# Shiny application for generating spatial distributions with constant density (per unit area)

rm(list = ls()) # clear memory

library(shiny)
library(dplyr)
library(ggplot2)
library(DT)
library(stringr)


# ====================================================================
# code to choose the spatial data file (.bgm)

wd <- "/Users/ric352/Documents/Projects/Fisheries/Atlantis/Setup Tool/Antarctic/"
setwd(wd)
bgm.file <- paste(wd, "BanzareAtlantis.bgm", sep = "")

# wd <- "/Users/ric352/Documents/Projects/Fisheries/Atlantis/Setup Tool/GBR/"
# setwd(wd)
# bgm.file <- paste(wd, "gbr_test.bgm", sep = "")

# wd <- "/Users/ric352/Documents/Projects/Fisheries/Atlantis/Setup Tool/SEAP/"
# setwd(wd)
# bgm.file <- paste(wd, "SEAP_extended_shelf.bgm", sep = "")

# wd <- "/Users/ric352/Documents/Projects/Fisheries/Atlantis/Setup Tool/Guam/"
# setwd(wd)
# bgm.file <- paste(wd, "Guam_utm1.bgm", sep = "")

# wd <- "/Users/ric352/Documents/Projects/Fisheries/Atlantis/Setup Tool/JFRE/"
# setwd(wd)
# bgm.file <- paste(wd, "JFRE_ll.bgm", sep = "")

# ====================================================================
# code to collect the spatial data and view

map.object <- make.dist.object(bgm.file)
sh.dist(map.object)

```